### ISSUE TITLE
OS users not getting created

### ISSUE THREAD

**Issue by Snowned0425** [HewlettPackard/jupyterhub-samlauthenticator#62]
This module only seems to work if I pre-create the OS users. It is not creating them on first login.

**Comment by distortedsignal** [comment]
Could you share your config file? Also, could you share what user your JupyterHub is running under? If you're trying to create users, you'll need to be running under a user that can create other users.

**Comment by Snowned0425** [comment]
I was running JupyterHub 1.1.0 as it was included as part of the AWS EMR I was running. It's a container and it does run as root. I decided to build a standalone 1.4.1 instance on an EC2 today, and everything works fine with it. So this just appears to be a bug in 1.1.0, which admittedly is very old.
